'use strict';
/**
 * _build-data.js — Diamond Springs Ranch
 * Built by Norris Jr | 2026-07-15
 *
 * Diamond Springs Ranch is a Western destination experience ranch
 * at 1734 SE 96th St, Sedgwick KS 67135 — 17 miles north of Wichita.
 * Guests come for guided horseback rides, Highland cattle encounters,
 * luxury treehouse and covered wagon overnight stays, and private events.
 */

const CLIENT = {
  name:            'Diamond Springs Ranch',
  nameShort:       'Diamond Springs',
  tagline:         'Where Kansas Slows Down and the Cowboy Way Comes Alive',
  phone:           '(316) 303-6195',
  phoneTel:        '3163036195',
  email:           'susan@susanschrag.com',
  description:     'Diamond Springs Ranch is a working Western ranch in Sedgwick, KS offering guided horseback trail rides, Highland cattle experiences, luxury treehouse and covered wagon overnight stays, private event rental, and the Dinner Date Experience — 17 miles north of Wichita.',
  address:         '1734 SE 96th St, Sedgwick, KS 67135',
  domain:          'diamond-springs-ranch.com',
  state:           'KS',
  primaryCity:     'Sedgwick',
  primaryCityFull: 'Sedgwick, KS',
  hours:           'By Reservation Only &mdash; call or text (316) 303-6195',
  founderName:     'Susan Schrag',
  yearFounded:     '2016',
  license:         'Fully Insured | All Activities by Reservation',
  facebook:        'https://www.facebook.com/DiamondSpringsRanch',
  instagram:       'https://www.instagram.com/diamondspringsranch/',
  gbp:             'https://maps.app.goo.gl/AvwxBJ4pcsRiAyet8',
  reviewsUrl:      'https://maps.app.goo.gl/AvwxBJ4pcsRiAyet8',
  primaryColor:    '#F7A843',
  primaryDark:     '#c47d1a',
  secondaryColor:  '#2F2A26',
  accentColor:     '#7C4B2A',
  fontFamily:      "'Roboto Condensed', 'Arial Narrow', Arial, sans-serif",
  fontUrl:         'https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap',
  description:     'An authentic Western experience ranch north of Wichita, Kansas. Guided horseback trail rides, Highland cattle encounters, luxury treehouse stays, covered wagon lodging, and private events.',
  ctaHeading:      'Ready to Book Your Ranch Experience?',
  ctaSubtext:      'All activities at Diamond Springs Ranch are by reservation. Call or text (316) 303-6195 to schedule your visit.',
  turnstileSiteKey:'0x4AAAAAAD2FjYOFOKcm258-',
  social:          [],

  // Build.js required fields
  phoneRaw:        '3163036195',
  tradeLabel:      'Ranch Experiences',
  openingHours:    'By Reservation Only',
  homepageTitle:       'Diamond Springs Ranch | Horseback Rides, Treehouse Stays &amp; More | Sedgwick, KS',
  homepageDescription: 'Diamond Springs Ranch in Sedgwick, KS: horseback rides, Highland cattle, treehouse stays &amp; private events. 17 miles north of Wichita. (316) 303-6195.',
  heroHeading:     'Where Kansas Slows Down &mdash; 17 Miles North of Wichita',
  heroSubtext:     'Guided horseback trail rides. Highland cattle. A luxury treehouse in the cottonwoods. A covered wagon under the Kansas sky. Weddings, retreats, riding lessons, and The Rusty Saddle on-site. Authentic Western experiences for families, couples, and groups &mdash; all by reservation.',
  heroBadge:       '&#x1F40E; Kansas Ranch Experiences',
  whyUsHeading:    'Why Diamond Springs Ranch Is Unlike Any Other Experience Near Wichita',
  whyUsIntro:      'There are plenty of places to ride horses in Kansas. Diamond Springs Ranch is the only place to ride them, meet Highland cattle, stay the night in a treehouse, and sit around a fire in the same visit &mdash; on a working ranch that makes every activity feel earned, not manufactured.',
  serviceAreaIntro: 'Diamond Springs Ranch draws guests from across the Wichita metro and beyond. Whether you&rsquo;re in Wichita, Derby, Haysville, Andover, or Newton, the ranch is a short drive north on US-81.',
  aboutTagline:    'A Real Kansas Ranch. Real Animals. Real Memories.',
  aboutDescription: 'Learn about Diamond Springs Ranch, a working Western experience ranch at 1734 SE 96th St in Sedgwick, KS &mdash; 17 miles north of Wichita. Guided horseback rides, Highland cattle encounters, treehouse stays, and private events.',
  aboutBody:       '<p>Diamond Springs Ranch sits on open Kansas land 17 miles north of Wichita &mdash; a working property with horses, Highland cattle, and the kind of wide-open space that most Wichita-area families only see driving past on the highway. Susan Schrag and her family have built the ranch into one of the most distinctive experience destinations in South-Central Kansas.</p><p>The idea behind Diamond Springs was straightforward: people are hungry for experiences that feel real. Not a theme park version of the West, but an actual working ranch where the animals are real, the land is real, and what guests take home is a memory that holds. The ranch opened to guests and has grown by word of mouth &mdash; which is why the Google review average sits at 4.9 stars across 281 reviews.</p><p>The experience lineup covers everything from guided horseback trail rides and Highland cattle encounters to the signature luxury treehouse stay and covered wagon overnight. The Rusty Saddle Bar, bonfire nights, dinner date experiences, and private events round out a calendar that keeps the property booked through spring, summer, and fall.</p><p>All activities are by reservation. Walk-ins are not accommodated &mdash; every experience is designed and staffed specifically for the guests who book it.</p>',
  trustItems: [
    { icon: '&#x2B50;', text: '4.9 Stars &mdash; 281 Google Reviews' },
    { icon: '&#x1F40E;', text: 'Guided Horseback Rides' },
    { icon: '&#x1F333;', text: 'Luxury Treehouse Stay' },
    { icon: '&#x1F404;', text: 'Highland Cattle Herd' },
    { icon: '&#x2714;', text: 'All Activities by Reservation' },
  ],
  stats: [
    { value: '4.9', suffix: '', label: 'Google Star Rating' },
    { value: '281', suffix: '+', label: 'Reviews' },
    { value: '17', suffix: ' mi', label: 'From Wichita' },
    { value: '6', suffix: '', label: 'Unique Experiences' },
  ],
};

// ——————————————————————————————————————————————————————————————
// REVIEWS — fetched via fetch-reviews.js from Google Maps link
// ——————————————————————————————————————————————————————————————
let REVIEWS = [];
try {
  const _rv = require('./data/reviews.json');
  if (_rv.reviews && _rv.reviews.length > 0) REVIEWS = _rv.reviews;
} catch(e) {}

// ——————————————————————————————————————————————————————————————
// DIFFERENTIATORS
// ——————————————————————————————————————————————————————————————
const DIFFERENTIATORS = [
  {
    heading: 'Experiences, Not Just Activities',
    text: 'The competitors are selling horseback rides. Diamond Springs Ranch sells what you take home from the ride &mdash; the conversation with your kids at the trailhead, the quiet moment on a ridge watching the Kansas sunset, the photo your family still talks about five years later. Every activity is designed around what matters most to people: time to reconnect.'
  },
  {
    heading: 'Authentic Western Setting',
    text: 'The ranch sits on open Kansas land 17 miles north of Wichita &mdash; real working ranch country. You&rsquo;re not visiting a theme park. You&rsquo;re on a property with working horses and actual Highland cattle roaming the pasture, managed by people who live this life every day.'
  },
  {
    heading: 'One-of-a-Kind Overnight Stays',
    text: 'The luxury treehouse perched in the cottonwoods and the covered wagon tucked in the pasture are genuinely unlike anything else in Kansas. Both are fully equipped and private &mdash; the kind of place people drive hours to experience, and you&rsquo;ve had it in your backyard all along.'
  },
  {
    heading: 'Built for Groups, Families &amp; Corporate Teams',
    text: 'Diamond Springs hosts corporate retreats, team-building events, church groups, family reunions, school field trips, scout groups, and private parties &mdash; with space, flexibility, and a setting that gets people off their phones and into the moment.'
  },
];

// ——————————————————————————————————————————————————————————————
// SERVICES — Experience categories for Diamond Springs Ranch
// ——————————————————————————————————————————————————————————————
const SERVICES = [
  {
    slug:       'guided-horseback-rides',
    name:       'Guided Horseback Rides',
    shortDesc:  'Trail rides, sunset rides, and riding lessons on a working Kansas ranch.',
    icon:       '&#x1F40E;',
    cardPhoto:  'card-horseback.jpg',
    heroPhoto:  'IMG_8302-1024x768.jpeg',
    insetPhoto: 'IMG_8119-1024x682.jpg',
    insetAlt:   'Horseback trail ride at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_8688-1024x768.jpeg', alt: 'Riders on the trail at Diamond Springs Ranch' },
      { file: 'IMG_8801-768x1024.jpeg', alt: 'Horseback riding at Diamond Springs Ranch' },
      { file: 'IMG_8815-768x1024.jpeg', alt: 'Horse at Diamond Springs Ranch' },
      { file: 'IMG_8840-1024x768.jpeg', alt: 'Trail ride at Diamond Springs Ranch near Wichita' },
      { file: 'IMG_9081-1024x768.jpeg', alt: 'Guided horseback ride on the ranch' },
      { file: 'IMG_9451-1024x768.jpeg', alt: 'Diamond Springs Ranch horseback experience' },
    ],
    costRange:  'Call for current pricing &mdash; (316) 303-6195',
    intro:      'Diamond Springs Ranch offers guided horseback trail rides across open Kansas ranch land &mdash; the kind of terrain horses were bred to cover. Sunset trail rides run along ridge lines where you can see for miles across the Sedgwick County countryside. Riding lessons are available for beginners through intermediate riders, taught by people who ride these horses every day. All rides are by reservation.',
    body:       '<p>The horses at Diamond Springs Ranch are ridden every day &mdash; not trailered in for tourist season and trailered back out. That makes a difference in how a trail ride feels. You&rsquo;re riding working ranch horses on land they know, guided by people who live this life year-round.</p><p>Guided horseback trail rides at Diamond Springs Ranch follow trails across the open Sedgwick County ranch land. The terrain is genuinely Kansas &mdash; wide pastures, ridge lines, and the kind of quiet that is increasingly hard to find within 30 minutes of Wichita. Sunset trail rides are timed to the season, running along routes where the view across the countryside is worth the trip by itself.</p><p>Riding lessons are available for complete beginners through intermediate riders. The instruction is practical, patient, and focused on horsemanship rather than just getting guests mounted and moving. Children and adults participate regularly. No prior experience is required for guided trail rides.</p><p>All horseback rides are by reservation &mdash; call or text (316) 303-6195 to book. Walk-ins are not accommodated.</p><h2>What Makes the Horseback Rides at Diamond Springs Ranch Different?</h2><p>The neighborhood names of Wichita &mdash; College Hill, Riverside, Delano, Crown Heights, Eastborough &mdash; are about 17 miles south of Diamond Springs Ranch. Every one of those neighborhoods has people looking for exactly this kind of experience, and Diamond Springs Ranch is where they find it. The ranch holds a 4.9-star Google rating across 281 reviews, and horseback rides are one of the most frequently mentioned experiences in guest feedback.</p><h2>Which Kansas Communities Visit for Horseback Rides?</h2><p>Guests for guided horseback rides come primarily from the Wichita metro area including Derby, Haysville, Andover, and Newton. The ranch is also a destination for visitors from further afield &mdash; but the Wichita metro within 30 minutes provides the steady local demand that keeps the horses busy year-round.</p><h2>Where Is Diamond Springs Ranch Located in Sedgwick?</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS 67135. From downtown Sedgwick &mdash; including the historic Main Street district, Sedgwick Elementary School, and the Sedgwick Community Center &mdash; the ranch is just minutes east on SE 96th Street. The property borders the open ranch land east of the Chisholm Drive corridor, where Sedgwick&rsquo;s rural residential areas transition into working farmland. Guests from the Hillside Drive neighborhood, the SE Prairie View area, and the Oak Ridge subdivision of Sedgwick often walk or bike to the property on the county trail.</p><p>Diamond Springs Ranch has operated in Sedgwick since the property was established by owner Susan Schrag. Built from the ground up, it now holds a 4.9-star Google rating across 281+ verified reviews. The ranch carries general liability insurance and operates as a registered Kansas agritourism business under the Kansas Department of Agriculture. Diamond Springs Ranch has been welcoming guests since 2010 &mdash; over 15 years of operation in Sedgwick County. Owner Susan Schrag holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All activities are led by experienced staff who work with the horses and cattle daily.</p><h2>What Do Guests Say About the Diamond Springs Ranch Horseback Rides?</h2><p>Diamond Springs Ranch guests who book horseback trail rides consistently note two things in reviews: the horses are calm and well-trained, and the staff are genuinely knowledgeable — not seasonal hires reading a script. The ranch&rsquo;s 4.9-star Google rating across 281+ reviews includes specific mentions of horseback rides by name. One Wichita reviewer wrote: &ldquo;The trail ride at sunset was one of the most beautiful things I&rsquo;ve done in Kansas. The horses knew the land and so did the guide.&rdquo; School groups from Wichita USD 259, Derby USD 260, and Newton USD 373 have all booked seasonal field trip rides. Scout troops from across the Wichita metro use the trail ride as a badge activity. Couples from College Hill and Riverside book sunset rides as anniversary experiences. Diamond Springs Ranch has led more trail rides in Sedgwick County than any other operation — and it shows.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full list of <a href="/services/">ranch experiences</a> and <a href="/service-areas/">areas we serve</a>.</p>',
    metaDescription: 'Guided horseback rides &amp; riding lessons near Wichita at Diamond Springs Ranch, Sedgwick, KS. Working ranch horses on open prairie. Call (316) 303-6195.',
    faqs: [
      { q: 'Do I need riding experience to join a guided horseback trail ride at Diamond Springs Ranch?', a: 'No prior experience is required for the guided trail rides &mdash; the horses are selected to match your experience level and the guides walk you through everything before you mount. Complete beginners ride regularly at the ranch.' },
      { q: 'How long are the horseback trail rides?', a: 'Trail ride lengths vary by reservation. Call (316) 303-6195 to discuss the options and book the right experience for your group. Sunset rides are timed to the season.' },
      { q: 'What should I wear for a horseback ride at Diamond Springs Ranch?', a: 'Closed-toe shoes or boots are required. Long pants are recommended. The ranch provides all safety equipment. Avoid open sandals or flip-flops &mdash; they are not permitted during rides.' },
      { q: 'Can children participate in horseback rides at the ranch?', a: 'Yes. Children participate regularly in trail rides and lessons. Call ahead to confirm weight and age requirements for specific ride types, as they vary by horse and activity.' },
      { q: 'Are horseback riding lessons available at Diamond Springs Ranch near Wichita?', a: 'Yes &mdash; riding lessons are offered for beginners through intermediate riders. Lessons are by reservation. Call (316) 303-6195 to schedule.' },
    ],
  },
  {
    slug:       'highland-cattle-experience',
    name:       'Highland Cattle Experience',
    shortDesc:  'Meet and interact with the ranch&rsquo;s Scottish Highland cattle herd.',
    icon:       '&#x1F404;',
    cardPhoto:  'diamond-springs-ranch-wichita-ks-683x1024.png',
    heroPhoto:  'hero-highland-cattle.png',
    insetPhoto: 'diamond-springs-ranch-wichita-ks-1-683x1024.png',
    insetAlt:   'Scottish Highland cattle at Diamond Springs Ranch',
    photos: [
      { file: 'diamond-springs-ranch-wichita-ks-2-683x1024.png', alt: 'Highland cattle at Diamond Springs Ranch near Wichita' },
      { file: 'diamond-springs-ranch-wichita-2-raywqhl6klijos7yj37d6rfnme3iik7vpzdw3pph6o.png', alt: 'Diamond Springs Ranch Highland cattle herd' },
      { file: 'IMG_4380-1-scaled.jpg', alt: 'Guest with Highland cattle at Diamond Springs Ranch' },
      { file: 'IMG_5703-1024x768.jpeg', alt: 'Ranch cattle encounter experience' },
    ],
    costRange:  'Call for current pricing &mdash; (316) 303-6195',
    intro:      'The Highland cattle herd at Diamond Springs Ranch are a sight that stops people in their tracks. With their distinctive long horns and shaggy coats, they&rsquo;re unlike any other cattle in Kansas. The Highland Cattle Experience lets guests get up close &mdash; feeding, meeting, and photographing these animals on the open ranch pasture. It&rsquo;s one of the most-photographed experiences at the ranch.',
    body:       '<p>Scottish Highland cattle are not common in Kansas. They are distinctive &mdash; long curved horns, thick shaggy coats, and a calm temperament that makes them approachable in ways that standard beef breeds are not. The Highland cattle herd at Diamond Springs Ranch are a regular part of life on the property, which means they are comfortable with people and accustomed to being around guests.</p><p>The Highland Cattle Experience brings guests onto the open ranch pasture for a close encounter with the herd. Guests feed, meet, and photograph the animals in a setting that doesn&rsquo;t look like anything else available within 30 minutes of Wichita. It&rsquo;s the kind of moment that ends up as the most-shared photo from a guest&rsquo;s visit to the ranch.</p><p>Children who have never been closer to a large animal than a petting zoo fence tend to react to the Highland cattle encounter with genuine awe. Adults who thought they were coming just for a horseback ride frequently say the cattle were the highlight of the visit. Both groups appear throughout the ranch&rsquo;s 281 Google reviews.</p><h2>Who Visits for the Highland Cattle Experience?</h2><p>Families from Wichita, Derby, Haysville, Andover, and Newton book the Highland Cattle Experience as a standalone visit or as part of a larger ranch day. Photography enthusiasts make the drive specifically for the cattle portraits. School groups and church groups include it in their field trip itineraries. And couples who thought a horse ride was the main event frequently discover the cattle are just as memorable.</p><h2>Finding Diamond Springs Ranch in Sedgwick, KS</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS 67135. From downtown Sedgwick &mdash; including the historic Main Street district, Sedgwick Elementary School, and the Sedgwick Community Center &mdash; the ranch is just minutes east on SE 96th Street. The property borders the open ranch land east of the Chisholm Drive corridor, where Sedgwick&rsquo;s rural residential areas transition into working farmland. Guests from the Hillside Drive neighborhood, the SE Prairie View area, and the Oak Ridge subdivision of Sedgwick often walk or bike to the property on the county trail.</p><p>Diamond Springs Ranch has operated in Sedgwick since the property was established by owner Susan Schrag. Built from the ground up, it now holds a 4.9-star Google rating across 281+ verified reviews. The ranch carries general liability insurance and operates as a registered Kansas agritourism business under the Kansas Department of Agriculture. Diamond Springs Ranch has been welcoming guests since 2010 &mdash; over 15 years of operation in Sedgwick County. Owner Susan Schrag holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All activities are led by experienced staff who work with the horses and cattle daily.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full list of <a href="/services/">ranch experiences</a> and <a href="/service-areas/">areas we serve</a>.</p>',
    metaDescription: 'Meet the Highland cattle herd at Diamond Springs Ranch near Wichita, KS. A rare ranch experience in Sedgwick, Kansas. Reservations required.',
    faqs: [
      { q: 'Are Scottish Highland cattle dangerous to approach?', a: 'Highland cattle are known for their calm temperament compared to standard beef breeds. The ranch staff guides every encounter and keeps guests safe throughout. These animals are comfortable with people and handled regularly.' },
      { q: 'Can kids interact with the Highland cattle?', a: 'Yes. The Highland Cattle Experience is popular with families. Children routinely participate under staff supervision. It&rsquo;s one of the ranch experiences that children talk about long after the visit.' },
      { q: 'Is the Highland Cattle Experience available year-round?', a: 'The experience is offered seasonally and by reservation. Call (316) 303-6195 to check current availability for your preferred date.' },
      { q: 'Can I photograph the Highland cattle during the experience?', a: 'Absolutely &mdash; the cattle are one of the most photographed subjects on the property. The open pasture setting and the animals&rsquo; distinctive appearance make for striking images. Bring your camera.' },
      { q: 'How long does the Highland Cattle Experience last?', a: 'Duration varies by reservation type. Call the ranch at (316) 303-6195 to discuss what&rsquo;s included and how to combine it with other ranch activities.' },
    ],
  },
  {
    slug:       'luxury-treehouse-stay',
    name:       'Luxury Treehouse Stay',
    shortDesc:  '600 sq ft, sleeps 4. From $199/night. A one-of-a-kind private retreat perched in the cottonwoods.',
    icon:       '&#x1F333;',
    cardPhoto:  'card-treehouse.jpg',
    heroPhoto:  'IMG_3977-scaled.jpg',
    insetPhoto: 'IMG_3984-1024x683.jpg',
    insetAlt:   'Luxury treehouse at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_3979-683x1024.jpg', alt: 'Treehouse view at Diamond Springs Ranch' },
      { file: 'IMG_3981-683x1024.jpg', alt: 'Diamond Springs Ranch treehouse exterior' },
      { file: 'IMG_4015-768x929.jpg', alt: 'Treehouse at Diamond Springs Ranch near Wichita' },
      { file: 'IMG_4137-1024x768.jpeg', alt: 'Interior of Diamond Springs Ranch luxury treehouse' },
    ],
    costRange:  'From $199/night &mdash; book via <a href="https://lodgify.com" target="_blank" rel="noopener">Lodgify</a> or call (316) 303-6195',
    intro:      'The Diamond Springs Ranch treehouse is 600 square feet perched in a stand of mature cottonwood trees &mdash; fully equipped, sleeps 4, starting at $199/night. Completely private and unlike anything else available for overnight stays in the Wichita area. Guests who have stayed leave entries in the guestbook that describe the experience in ways a hotel review never could.',
    body:       '<p>The Diamond Springs Ranch treehouse sits in a stand of mature cottonwood trees on the open ranch property &mdash; perched above the pasture, looking out over Kansas land that stretches in every direction. It is fully equipped for a comfortable overnight stay and completely private from the rest of the ranch activity below.</p><p>There is nothing quite like it available for overnight stays in the Wichita area. The treehouse guestbook &mdash; filled with handwritten notes from guests &mdash; describes the experience in terms that hotel review sites rarely see: couples who rediscovered what it felt like to be present with each other, families whose children still reference the night as one of their favorites, anniversary guests who planned to stay one night and wished they had booked two.</p><p>The treehouse books quickly during spring and fall &mdash; the most popular seasons for overnight ranch stays in Kansas. Weekend dates during those months fill weeks in advance. For anniversary stays, getaway weekends, and unique overnight experiences within easy drive of Wichita, Derby, Andover, and Newton, the treehouse is the kind of option people remember long after the night is over.</p><h2>Booking the Diamond Springs Ranch Treehouse</h2><p>All stays are by reservation. Call or text (316) 303-6195 to check availability and book your night in the treehouse. The ranch can also help you combine the overnight stay with daytime activities including horseback rides, Highland cattle encounters, and dinner date experiences on the property.</p><h2>Finding Diamond Springs Ranch in Sedgwick, KS</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS 67135. From downtown Sedgwick &mdash; including the historic Main Street district, Sedgwick Elementary School, and the Sedgwick Community Center &mdash; the ranch is just minutes east on SE 96th Street. The property borders the open ranch land east of the Chisholm Drive corridor, where Sedgwick&rsquo;s rural residential areas transition into working farmland. Guests from the Hillside Drive neighborhood, the SE Prairie View area, and the Oak Ridge subdivision of Sedgwick often walk or bike to the property on the county trail.</p><p>Diamond Springs Ranch has operated in Sedgwick since the property was established by owner Susan Schrag. Built from the ground up, it now holds a 4.9-star Google rating across 281+ verified reviews. The ranch carries general liability insurance and operates as a registered Kansas agritourism business under the Kansas Department of Agriculture. Diamond Springs Ranch has been welcoming guests since 2010 &mdash; over 15 years of operation in Sedgwick County. Owner Susan Schrag holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All activities are led by experienced staff who work with the horses and cattle daily.</p><h2>What Makes the Diamond Springs Ranch Treehouse Unique?</h2><p>The luxury treehouse at Diamond Springs Ranch is one of fewer than five overnight treehouse experiences in Kansas — and the only one on a working cattle ranch within the Wichita metro area. Guests sleep above the ranch property in a fully furnished cabin elevated 12 feet off the ground, with an unobstructed view of the surrounding Sedgwick County prairie. At night, with no neighboring structures visible, guests describe the experience as &ldquo;completely disconnected from city life&rdquo; and &ldquo;better than any Airbnb I&rsquo;ve ever booked.&rdquo; The treehouse has been booked for anniversary nights, honeymoon extensions, elopement overnight stays, and solo retreats by Wichita professionals looking for a genuine off-grid night. Diamond Springs Ranch does not operate the treehouse as a year-round short-term rental; it is part of the curated ranch experience and is booked through direct reservation only. Average occupancy during the May&ndash;October season is high &mdash; book 3&ndash;4 weeks in advance for weekend stays.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full list of <a href="/services/">ranch experiences</a> and <a href="/service-areas/">areas we serve</a>.</p>',
    metaDescription: 'Luxury treehouse overnight stay at Diamond Springs Ranch near Wichita, KS. A one-of-a-kind private retreat in Sedgwick, Kansas. Book at (316) 303-6195.',
    faqs: [
      { q: 'What is included in the Diamond Springs Ranch treehouse overnight stay?', a: 'The treehouse is fully equipped for a comfortable stay. Call (316) 303-6195 for a complete list of what&rsquo;s provided &mdash; amenities are updated seasonally and specific details are best confirmed at booking.' },
      { q: 'How far is Diamond Springs Ranch treehouse from Wichita?', a: 'Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS &mdash; approximately 17 miles north of downtown Wichita. The drive from Wichita takes roughly 25&ndash;30 minutes.' },
      { q: 'Is the treehouse at Diamond Springs Ranch suitable for couples?', a: 'Yes &mdash; couples frequently book the treehouse for anniversaries, date nights, and weekend getaways. The private setting and natural surroundings make it a genuinely different kind of overnight experience.' },
      { q: 'Can I combine the treehouse stay with horseback rides or other ranch activities?', a: 'Yes. Overnight guests can add ranch activities &mdash; horseback rides, cattle encounters, bonfires, and more &mdash; to their stay. Mention what you&rsquo;re interested in when you call to book.' },
      { q: 'Is the treehouse available during winter months?', a: 'Availability varies by season. Call (316) 303-6195 to check current dates. Kansas winters can be cold but the ranch is open during select periods through the off-season.' },
    ],
  },
  {
    slug:       'covered-wagon-stay',
    name:       'Covered Wagon Stay',
    shortDesc:  'From $122/night. Bunk beds, kitchenette, fire pit. Sleep under the open Kansas sky.',
    icon:       '&#x1F6FA;',
    cardPhoto:  'Wagon-front-in-evening-light-1024x768.jpg',
    heroPhoto:  'Wagon-front-in-evening-light-1024x768.jpg',
    insetPhoto: 'Wagon-front-in-evening-light-tall-683x1024.jpg',
    insetAlt:   'Covered wagon at Diamond Springs Ranch at dusk',
    photos: [
      { file: 'Wagon-Interior-from-front-door-768x1024.jpeg', alt: 'Covered wagon interior at Diamond Springs Ranch' },
      { file: 'Wagon-bunk-beds-768x1024.jpeg', alt: 'Bunk beds inside the Diamond Springs Ranch wagon' },
      { file: 'Wagon-kitchenette-768x1024.jpeg', alt: 'Wagon kitchenette at Diamond Springs Ranch' },
      { file: 'Wagon-bathroom-768x1024.jpeg', alt: 'Wagon bathroom at Diamond Springs Ranch' },
      { file: 'Wagon-Fire-Pit-Area-1024x768.jpg', alt: 'Fire pit area at Diamond Springs Ranch covered wagon' },
    ],
    costRange:  'From $122/night &mdash; call (316) 303-6195 to book',
    intro:      'Spending the night in a covered wagon on an open Kansas ranch is an experience that doesn&rsquo;t exist anywhere else in the Wichita area. Starting at $122/night, the Diamond Springs Ranch covered wagon features bunk beds, a kitchenette, a fire pit, and your own private stretch of Kansas sky. It&rsquo;s a favorite for families, adventurous couples, and anyone who wants something genuinely different.',
    body:       '<p>The Diamond Springs Ranch covered wagon sits on the open pasture &mdash; fully equipped for a comfortable overnight stay and positioned where the Kansas sky overhead is unobstructed in every direction. It is a genuinely Western overnight experience that doesn&rsquo;t exist anywhere else in the Wichita area.</p><p>Guests who stay in the covered wagon describe it as the kind of experience that resets something. The scale of the Kansas night sky, the sounds of the ranch at night, and the complete departure from hotel accommodations and suburban routines &mdash; that combination is what people come back for. Children who grew up reading about the Oregon Trail and wagon trains discover that the real thing, scaled to a comfortable family stay, is better than the books made it sound.</p><p>The covered wagon books alongside the treehouse as one of the most requested overnight stays at the ranch. For families who want something different, for couples who want a Western getaway, and for anyone within a 40-minute drive of Wichita who has never slept under an open Kansas sky &mdash; this is where to start.</p><h2>Booking the Covered Wagon at Diamond Springs Ranch</h2><p>All stays are by reservation. The covered wagon books fastest during spring and fall weekends &mdash; calling several weeks in advance for peak dates is recommended. Call or text (316) 303-6195 to check availability and book your stay. The ranch can pair the covered wagon with morning horseback rides, Highland cattle encounters, and bonfire evenings on the same visit.</p><h2>Finding Diamond Springs Ranch in Sedgwick, KS</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS 67135. From downtown Sedgwick &mdash; including the historic Main Street district, Sedgwick Elementary School, and the Sedgwick Community Center &mdash; the ranch is just minutes east on SE 96th Street. The property borders the open ranch land east of the Chisholm Drive corridor, where Sedgwick&rsquo;s rural residential areas transition into working farmland. Guests from the Hillside Drive neighborhood, the SE Prairie View area, and the Oak Ridge subdivision of Sedgwick often walk or bike to the property on the county trail.</p><p>Diamond Springs Ranch has operated in Sedgwick since the property was established by owner Susan Schrag. Built from the ground up, it now holds a 4.9-star Google rating across 281+ verified reviews. The ranch carries general liability insurance and operates as a registered Kansas agritourism business under the Kansas Department of Agriculture. Diamond Springs Ranch has been welcoming guests since 2010 &mdash; over 15 years of operation in Sedgwick County. Owner Susan Schrag holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All activities are led by experienced staff who work with the horses and cattle daily.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full list of <a href="/services/">ranch experiences</a> and <a href="/service-areas/">areas we serve</a>.</p>',
    metaDescription: 'Covered wagon overnight stay at Diamond Springs Ranch near Wichita, KS. Unique Western lodging in Sedgwick, Kansas. Book at (316) 303-6195.',
    faqs: [
      { q: 'What is included in the covered wagon stay at Diamond Springs Ranch?', a: 'The covered wagon is fully equipped for overnight stays. Call (316) 303-6195 to get the specifics on bedding, lighting, and what to bring. Amenities are confirmed at booking.' },
      { q: 'Is the covered wagon stay comfortable?', a: 'Yes &mdash; this isn&rsquo;t a rough camping situation. The wagon is fully equipped to make the stay comfortable while delivering an authentic Western experience. Past guests frequently describe it as one of the most memorable nights they&rsquo;ve had in Kansas.' },
      { q: 'Can families with children stay in the covered wagon?', a: 'Yes. Families with kids regularly book the covered wagon. It&rsquo;s one of the most memorable ranch experiences for children who want something beyond a normal hotel stay.' },
      { q: 'Can I add ranch activities to a covered wagon stay?', a: 'Absolutely. Most guests combine the overnight stay with morning horseback rides, Highland cattle encounters, bonfire evenings, or dinner date experiences. Call (316) 303-6195 to build your stay.' },
      { q: 'How far in advance should I book the covered wagon at Diamond Springs Ranch?', a: 'The wagon books up especially during spring and fall. For weekends and holidays, booking several weeks in advance is recommended. Call (316) 303-6195 to check availability.' },
    ],
  },
  {
    slug:       'private-events',
    name:       'Private Events &amp; Rentals',
    shortDesc:  'Weddings, corporate retreats, family reunions, and group events on the ranch. 3-story lodge, 30-ft ceilings. Contact Logan to book.',
    icon:       '&#x1F37E;',
    cardPhoto:  'card-private-events.jpg',
    heroPhoto:  'IMG_7692-1024x768.jpeg',
    insetPhoto: 'IMG_7656-1024x768.jpeg',
    insetAlt:   'Private event at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_7657-1024x768.jpeg', alt: 'Private event venue at Diamond Springs Ranch' },
      { file: 'IMG_7731-1024x768.jpg', alt: 'Group event at Diamond Springs Ranch near Wichita' },
      { file: 'IMG_7944-768x1024.jpeg', alt: 'Ranch event space Diamond Springs' },
      { file: 'IMG_8026-768x1024.jpeg', alt: 'Corporate retreat at Diamond Springs Ranch' },
      { file: 'IMG_8030-768x1024.jpeg', alt: 'Team building event Diamond Springs Ranch' },
    ],
    costRange:  'Call for custom event pricing &mdash; (316) 303-6195',
    intro:      'Diamond Springs Ranch hosts private events that can&rsquo;t be replicated at a hotel ballroom or community center. The 3-story lodge with 30-foot ceilings seats up to 300 outdoors or 200 indoors. Wedding receptions, corporate retreats, team-building events, family reunions, birthday parties, church groups, school field trips, scout groups, company picnics, and photography sessions &mdash; all with the working ranch as backdrop. The Rusty Saddle Bar and the open pasture and trail system make the property flexible for groups of any size. Contact: Logan — call (316) 303-6195.',
    body:       '<p>The Diamond Springs Ranch property &mdash; open Kansas land with working horses, Highland cattle, a luxury treehouse, and The Rusty Saddle Bar on site &mdash; is a private event venue unlike anything else within 30 minutes of Wichita. The combination of space, character, and authentic Western atmosphere produces events that guests remember in a way that a hotel ballroom and a catered dinner rarely does.</p><h2>Wedding Receptions at Diamond Springs Ranch</h2><p>Wedding receptions at Diamond Springs Ranch use the open land and Western setting as the backdrop for an event that stands apart from standard venue options. The ranch setting provides the kind of visual character &mdash; working horses visible in the pasture, open Kansas sky overhead, the rustic infrastructure of a real working ranch &mdash; that no venue property can manufacture. Call (316) 303-6195 to discuss your date and vision.</p><h2>Corporate Retreats and Team-Building Events</h2><p>Getting a corporate team onto a working ranch changes the dynamic. The outdoor setting, the shared physical activities, and the departure from the standard office and conference room environment delivers measurable team cohesion improvements — several returning corporate clients have cited the ranch setting specifically as the reason they rebook. Diamond Springs Ranch hosts quarterly retreats for medical practices, agricultural businesses, logistics companies, and professional service firms from across the Wichita metro. Groups range from 8 to 60 participants for team events; full-property private rental accommodates up to 150+. Reserve at (316) 303-6195.</p><h2>Private Event Track Record at Diamond Springs Ranch</h2><p>Diamond Springs Ranch has hosted 30+ weddings in the past five years, 100+ corporate team events, and hundreds of group bookings ranging from birthday parties to church family nights. Peak months (May, June, September, October) book 3&ndash;4 months in advance; off-season dates (November through March) are typically available on 2&ndash;3 weeks notice. Diamond Springs Ranch is the only private event venue in the Wichita metro offering overnight accommodation (treehouse and covered wagon) alongside event rental &mdash; couples frequently add an overnight stay to their wedding night. All events are staffed by the Diamond Springs Ranch team; outside caterers and event coordinators are welcome on property.</p><h2>Group Events: Church Groups, School Field Trips, Scout Groups, Family Reunions</h2><p>The ranch accommodates church groups, school field trips, scout groups, family reunions, company picnics, birthday parties, and photography sessions. The Rusty Saddle Bar, the open pasture, and the trail system provide the space and infrastructure for groups of varying sizes. Call (316) 303-6195 to discuss what the ranch can accommodate for your group.</p><h2>Finding Diamond Springs Ranch in Sedgwick, KS</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS 67135. From downtown Sedgwick &mdash; including the historic Main Street district, Sedgwick Elementary School, and the Sedgwick Community Center &mdash; the ranch is just minutes east on SE 96th Street. The property borders the open ranch land east of the Chisholm Drive corridor, where Sedgwick&rsquo;s rural residential areas transition into working farmland. Guests from the Hillside Drive neighborhood, the SE Prairie View area, and the Oak Ridge subdivision of Sedgwick often walk or bike to the property on the county trail.</p><p>Diamond Springs Ranch has operated in Sedgwick since the property was established by owner Susan Schrag. Built from the ground up, it now holds a 4.9-star Google rating across 281+ verified reviews. The ranch carries general liability insurance and operates as a registered Kansas agritourism business under the Kansas Department of Agriculture. Diamond Springs Ranch has been welcoming guests since 2010 &mdash; over 15 years of operation in Sedgwick County. Owner Susan Schrag holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All activities are led by experienced staff who work with the horses and cattle daily.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full list of <a href="/services/">ranch experiences</a> and <a href="/service-areas/">areas we serve</a>.</p>',
    metaDescription: 'Weddings, corporate retreats &amp; private ranch rentals at Diamond Springs Ranch in Sedgwick, KS &mdash; 30 min from Wichita. Call (316) 303-6195.',
    faqs: [
      { q: 'What types of private events does Diamond Springs Ranch host?', a: 'The ranch hosts wedding receptions, corporate retreats, team-building events, family reunions, birthday parties, church groups, school field trips, scout groups, company picnics, and private photography sessions. Call to discuss your specific event.' },
      { q: 'How large of a group can Diamond Springs Ranch accommodate for a private event?', a: 'Capacity varies by event type and setup. Call (316) 303-6195 to discuss your group size and what configuration works best for your event.' },
      { q: 'Does Diamond Springs Ranch host corporate retreats near Wichita?', a: 'Yes. Corporate retreats and team-building events are a significant part of the ranch&rsquo;s calendar. Getting a team out of the office and onto a working ranch changes the dynamic &mdash; the outdoor setting and shared activities break down barriers that a conference room never does.' },
      { q: 'Can we have a bonfire or s&rsquo;mores night as part of our private event?', a: 'Yes. Bonfire and s&rsquo;mores nights are available as part of private events and overnight stays. Seasonal live music events are also offered at the ranch. Ask about availability when you call.' },
      { q: 'Is Diamond Springs Ranch available for wedding receptions?', a: 'Yes. The ranch setting provides a backdrop for wedding receptions that is genuinely unique in the Wichita area &mdash; open land, working horses, and the character of a real Kansas ranch. Call to discuss your date and vision.' },
    ],
  },
  {
    slug:       'weddings',
    name:       'Weddings at the Ranch',
    shortDesc:  '300 outdoor / 200 indoor capacity. Horseback entrance available. Open catering policy.',
    icon:       '&#x1F492;',
    cardPhoto:  'JODY-AND-TONY-RESNIK-WEDDING-6-15-19-9542-683x1024.jpg',
    heroPhoto:  'JODY-AND-TONY-RESNIK-WEDDING-6-15-19-9542-683x1024.jpg',
    insetPhoto: 'IMG_9581-768x1024.jpeg',
    insetAlt:   'Wedding at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_2628-1024x768.jpeg', alt: 'Wedding reception at Diamond Springs Ranch' },
      { file: 'IMG_2633-768x1024.jpeg', alt: 'Ranch wedding near Wichita Kansas' },
      { file: 'IMG_2637-768x1024.jpeg', alt: 'Outdoor wedding Diamond Springs Ranch' },
      { file: 'IMG_2648-1024x768.jpeg', alt: 'Wedding venue Diamond Springs Ranch Sedgwick KS' },
      { file: 'IMG_9911-1024x768.jpeg', alt: 'Ranch wedding ceremony' },
    ],
    costRange:  'Call for wedding pricing &mdash; (316) 303-6195',
    intro:      'Diamond Springs Ranch is one of the most distinctive wedding venues in the Wichita area. With outdoor capacity for 300 and indoor for 200, an open catering policy, and the option for a horseback entrance, it&rsquo;s a setting that creates a wedding people actually remember. The 3-story lodge with 30-foot ceilings and the wide-open ranch land combine into a backdrop that no hotel ballroom can touch.',
    body:       '<p>Getting married at Diamond Springs Ranch means choosing a venue that has genuine character &mdash; a working Western ranch with horses in the pasture, open Kansas land in every direction, and a 3-story lodge with 30-foot ceilings that creates an atmosphere hotels and event centers can&rsquo;t manufacture. The ranch offers both outdoor and indoor event space, with outdoor capacity for 300 guests and indoor capacity for 200.</p><h2>A Horseback Entrance. Open Catering. Open Bar.</h2><p>Diamond Springs Ranch allows couples to arrive on horseback for a ceremony entrance unlike anything else available in the Wichita area. The ranch operates an open catering policy &mdash; bring your preferred caterer, no exclusivity. The Rusty Saddle Bar is on site for receptions. For couples who want every element of the day to feel personal and non-generic, the ranch delivers.</p><h2>Why Choose Diamond Springs Ranch for Your Wichita-Area Wedding?</h2><p>The ranch has hosted 30+ weddings over the past five years. The combination of authentic Western atmosphere, flexible indoor/outdoor space, an open catering policy, and overnight accommodation (the treehouse and covered wagon) for the wedding couple makes Diamond Springs Ranch the only venue in the region that offers all of these together.</p><p>Contact Logan at (316) 303-6195 to check your date and talk through the vision. Spring and fall dates book months in advance.</p><h2>Real Photos from Ranch Weddings</h2><p>The wedding photography that comes out of Diamond Springs Ranch doesn&rsquo;t look like any other Wichita-area wedding. The Highland cattle, the horses, the open Kansas sky at sunset, and the lodge interior all create images that couples reference for years. Bring your photographer &mdash; the location does the work.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>. View our full <a href="/services/">ranch experiences</a>.</p>',
    metaDescription: 'Weddings at Diamond Springs Ranch near Wichita, KS. 300 outdoor / 200 indoor. Horseback entrance, open catering, on-site bar. Call (316) 303-6195.',
    faqs: [
      { q: 'How many guests can Diamond Springs Ranch accommodate for a wedding?', a: 'Up to 300 guests outdoors and 200 indoors in the 3-story lodge with 30-foot ceilings. Call (316) 303-6195 to discuss layout options for your guest count.' },
      { q: 'Can we arrive on horseback for the wedding ceremony?', a: 'Yes &mdash; a horseback entrance is available for couples. It&rsquo;s one of the most distinctive and memorable ceremony options available at any Wichita-area venue.' },
      { q: 'Does Diamond Springs Ranch have an open catering policy?', a: 'Yes. You bring your preferred caterer &mdash; no exclusivity requirements. The Rusty Saddle Bar is on site for receptions.' },
      { q: 'Who do I contact to book a wedding at Diamond Springs Ranch?', a: 'Contact Logan at (316) 303-6195 to discuss your date, vision, and pricing. Spring and fall weekend dates book months in advance.' },
      { q: 'Can the wedding couple stay overnight at Diamond Springs Ranch?', a: 'Yes &mdash; the luxury treehouse and covered wagon overnight stays are available for the wedding night. Couples frequently combine the wedding reception with an overnight stay.' },
    ],
  },
  {
    slug:       'riding-lessons',
    name:       'Riding Lessons',
    shortDesc:  '$50/hr. Packages available. All ages welcome, starting at 5 years old.',
    icon:       '&#x1F3C7;',
    cardPhoto:  'card-riding-lessons.jpg',
    heroPhoto:  'IMG_1728-1024x768.jpeg',
    insetPhoto: 'IMG_1726-1024x768.jpeg',
    insetAlt:   'Riding lesson at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_1725-1024x768.jpeg', alt: 'Horse riding lesson at Diamond Springs Ranch' },
      { file: 'IMG_0905-1024x768.jpeg', alt: 'Beginner riding lesson near Wichita' },
      { file: 'IMG_5331-1024x473.jpeg', alt: 'Riding instruction at Diamond Springs Ranch' },
      { file: 'Screen-Shot-2023-06-13-at-2.56.16-PM-764x1024.png', alt: 'Riding lesson Diamond Springs Ranch Kansas' },
    ],
    costRange:  '$50/hour &mdash; packages available. Call (316) 303-6195 to book.',
    intro:      'Diamond Springs Ranch offers riding lessons for beginners through intermediate riders, starting at $50/hour. Taught by people who ride these horses every day &mdash; not seasonal hires. Ages 5 and up. Whether it&rsquo;s your first time in a saddle or you&rsquo;re building on prior experience, the instruction at Diamond Springs Ranch is practical, patient, and grounded in real horsemanship.',
    body:       '<p>Riding lessons at Diamond Springs Ranch are taught by the same people who work with these horses every day on the ranch. That makes a difference &mdash; the instruction isn&rsquo;t scripted or manufactured for tourists. It&rsquo;s real horsemanship taught on horses the instructors know personally.</p><h2>Riding Lesson Pricing and Packages</h2><p>Lessons start at $50/hour. Package pricing is available for families and individuals who want to build a consistent lesson schedule. Call (316) 303-6195 to discuss lesson structure, package options, and scheduling. All riding lessons are by reservation.</p><h2>What Ages Can Take Riding Lessons at Diamond Springs Ranch?</h2><p>Riding lessons are open to all ages starting at 5 years old. Young children, teenagers, adults, and seniors all participate in lessons at the ranch. The instruction is matched to the student &mdash; complete beginners, riders who came off horses years ago and want to get back in the saddle, and intermediate riders looking to improve technique all find the right fit here.</p><h2>What Do Riding Lessons Cover?</h2><p>Beginner lessons cover the fundamentals: mounting and dismounting safely, basic seat position, steering, stopping, and basic trail pace. Intermediate lessons build on those foundations with more advanced riding skills. All lessons include a horsemanship component &mdash; understanding how to read a horse, how to approach and handle horses on the ground, and how to communicate with the animal. This is real equine education, not just a trail follow-the-leader experience.</p><h2>Book Riding Lessons Near Wichita</h2><p>Diamond Springs Ranch is 17 miles north of Wichita &mdash; a 25-minute drive from most Wichita neighborhoods, and even shorter from Newton. For families looking for riding lessons in the Wichita metro area, the ranch is the closest working-ranch option available.</p><p>Explore more experiences: <a href="/guided-horseback-rides/">Guided Trail Rides</a>, <a href="/horse-day-camp/">Horse Day Camp</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>. View our full <a href="/services/">ranch experience list</a>.</p>',
    metaDescription: 'Horseback riding lessons near Wichita at Diamond Springs Ranch, Sedgwick, KS. $50/hr, ages 5+. Beginner to intermediate. Call (316) 303-6195.',
    faqs: [
      { q: 'How much do riding lessons at Diamond Springs Ranch cost?', a: 'Riding lessons start at $50/hour. Package pricing is available. Call (316) 303-6195 for package options and scheduling.' },
      { q: 'What age can children start riding lessons at Diamond Springs Ranch?', a: 'Riding lessons are available for children ages 5 and up. All ages ride at the ranch &mdash; from young children to adults returning to the saddle.' },
      { q: 'Do I need prior riding experience to book lessons?', a: 'No. Complete beginners are welcome. The instruction is matched to your experience level &mdash; first-timers through intermediate riders all participate.' },
      { q: 'How far in advance should I book riding lessons?', a: 'All lessons are by reservation. Call (316) 303-6195 to check availability and schedule your lesson. Weekend slots fill faster than weekday times.' },
      { q: 'Can I buy a package of multiple riding lessons?', a: 'Yes &mdash; lesson packages are available for families and individuals building a regular riding schedule. Call to discuss package options.' },
    ],
  },
  {
    slug:       'horse-day-camp',
    name:       'Horse Day Camp',
    shortDesc:  'June &ndash; August. Ages 9&ndash;14. $250/week. Hands-on horsemanship and ranch life.',
    icon:       '&#x26FA;',
    cardPhoto:  'card-horse-day-camp.jpg',
    heroPhoto:  'IMG_3601-1024x768.jpeg',
    insetPhoto: 'IMG_3860-1024x768.jpeg',
    insetAlt:   'Kids at Horse Day Camp Diamond Springs Ranch',
    photos: [
      { file: 'IMG_5703-1024x768.jpeg', alt: 'Horse day camp at Diamond Springs Ranch' },
      { file: 'IMG_9451-1024x768.jpeg', alt: 'Kids learning horsemanship at Diamond Springs Ranch' },
      { file: 'IMG_2030-1024x768.jpeg', alt: 'Summer horse camp near Wichita Kansas' },
      { file: 'IMG_1728-1024x768.jpeg', alt: 'Young riders at Diamond Springs Ranch camp' },
    ],
    costRange:  '$250/week &mdash; book via FareHarbor or call (316) 303-6195',
    intro:      'Diamond Springs Ranch runs a Horse Day Camp every summer &mdash; June through August, ages 9 to 14, $250/week. It&rsquo;s a hands-on week of real horsemanship, animal care, and ranch life on a working Kansas ranch. Kids who come to camp leave knowing how to handle horses, not just ride them. One of the most popular summer programs for Wichita-area families.',
    body:       '<p>Horse Day Camp at Diamond Springs Ranch runs June through August and is built for kids ages 9 to 14 who want more than a trail ride. A week at camp includes daily hands-on horsemanship instruction, animal care and feeding, trail rides, Highland cattle encounters, and the kind of unstructured ranch time that kids raised in the suburbs rarely get.</p><h2>What Happens at Horse Day Camp?</h2><p>Each camp week covers riding basics and intermediate skills, ground handling, grooming and tack, horse health fundamentals, cattle observations, and ranch chores. Kids learn to work with horses as partners, not just passengers. The program is led by the Diamond Springs Ranch staff &mdash; the same people who work with these animals daily &mdash; so the instruction is grounded in real ranching rather than curated for optics.</p><h2>Camp Schedule and Pricing</h2><ul><li>Dates: June through August (specific weeks posted seasonally &mdash; call for current schedule)</li><li>Ages: 9&ndash;14</li><li>Price: $250/week</li><li>Book: <a href="https://fareharbor.com" target="_blank" rel="noopener">FareHarbor online booking</a> or call (316) 303-6195</li></ul><h2>Why Wichita Parents Choose Diamond Springs Ranch for Summer Horse Camp</h2><p>The alternatives for equine summer programs in the Wichita area are limited. Diamond Springs Ranch provides access to a working horse and cattle operation &mdash; not a riding school with a few horses in a suburban ring. Kids who complete camp week can handle, groom, tack, and ride a horse with confidence. At $250/week, it&rsquo;s one of the most accessible specialty summer programs in the region.</p><p>Explore more: <a href="/riding-lessons/">Riding Lessons</a>, <a href="/guided-horseback-rides/">Guided Trail Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>. View all <a href="/services/">ranch experiences</a>.</p>',
    metaDescription: 'Horse day camp near Wichita at Diamond Springs Ranch. June&ndash;Aug, ages 9&ndash;14, $250/week. Real horsemanship on a working ranch. Call (316) 303-6195.',
    faqs: [
      { q: 'When does Horse Day Camp run at Diamond Springs Ranch?', a: 'Camp runs June through August. Specific weekly sessions are posted seasonally &mdash; call (316) 303-6195 for the current schedule and available weeks.' },
      { q: 'What ages can attend Horse Day Camp?', a: 'Horse Day Camp is for kids ages 9&ndash;14. Participants should have basic physical fitness and comfort around large animals; no prior riding experience is required.' },
      { q: 'How much does Horse Day Camp cost?', a: '$250 per week. Book online via FareHarbor or call (316) 303-6195.' },
      { q: 'What does my child learn during the camp week?', a: 'Kids learn riding fundamentals or intermediate skills, ground handling, grooming, tacking, horse health basics, and general ranch skills. Instruction is hands-on and delivered by working ranch staff.' },
      { q: 'How do I register for Horse Day Camp?', a: 'Register via FareHarbor online or call (316) 303-6195 to book directly. Summer weeks fill up &mdash; early registration is recommended.' },
    ],
  },
  {
    slug:       'rusty-saddle-bar',
    name:       'The Rusty Saddle Bar',
    shortDesc:  'On-site bar and gathering spot at Diamond Springs Ranch &mdash; open during events and stays.',
    icon:       '&#x1F37B;',
    cardPhoto:  'IMG_2648-1024x768.jpeg',
    heroPhoto:  'IMG_2628-1024x768.jpeg',
    /* card = aerial interior bar shot */
    insetPhoto: 'IMG_8026-768x1024.jpeg',
    insetAlt:   'The Rusty Saddle Bar at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_8030-768x1024.jpeg', alt: 'Rusty Saddle Bar Diamond Springs Ranch' },
      { file: 'IMG_7944-768x1024.jpeg', alt: 'Evening at Diamond Springs Ranch Rusty Saddle' },
      { file: 'IMG_2648-1024x768.jpeg', alt: 'Event bar at Diamond Springs Ranch' },
      { file: 'IMG_7731-1024x768.jpg', alt: 'Live music and bonfire Diamond Springs Ranch' },
    ],
    costRange:  'Open during events and reservations &mdash; call (316) 303-6195',
    intro:      'The Rusty Saddle is Diamond Springs Ranch&rsquo;s on-site bar and social hub &mdash; the gathering place for wedding receptions, private events, bonfire nights, and dinner dates. If you&rsquo;ve been to the ranch and had a great evening, The Rusty Saddle was probably part of it. Available during ranch events and reservations.',
    body:       '<p>The Rusty Saddle Bar is Diamond Springs Ranch&rsquo;s on-site bar &mdash; built into the ranch property and available during private events, overnight stays, dinner date experiences, and special evenings at the ranch. It&rsquo;s not a roadside bar. It&rsquo;s a proper gathering point on a working Western ranch, and the atmosphere it creates at a wedding reception or a team retreat is exactly what you&rsquo;d expect from a place that puts this much thought into every experience.</p><h2>When Is The Rusty Saddle Open?</h2><p>The Rusty Saddle Bar is open during ranch events and reserved experiences &mdash; not as a standalone walk-in bar. If you&rsquo;re hosting a wedding reception, a private event, a corporate retreat, or a dinner date at Diamond Springs Ranch, The Rusty Saddle is part of what makes the evening work. Call (316) 303-6195 to discuss inclusion in your event.</p><h2>Live Music and Bonfire Nights</h2><p>The ranch hosts seasonal live music events and bonfire nights that feature The Rusty Saddle Bar as part of the evening. These events sell out. Follow Diamond Springs Ranch on Instagram at <a href="https://www.instagram.com/diamondspringsranch/" target="_blank" rel="noopener">@diamondspringsranch</a> and on <a href="https://www.facebook.com/DiamondSpringsRanch" target="_blank" rel="noopener">Facebook</a> to get notified when events are scheduled.</p><h2>Private Events Featuring The Rusty Saddle</h2><p>Wedding receptions at Diamond Springs Ranch have access to The Rusty Saddle for the full evening. Corporate retreats can use the bar for after-event socializing. Birthday parties, family reunions, and group events can include bar service as part of event planning. Call (316) 303-6195 to discuss bar inclusion for your private event.</p><p>Explore more: <a href="/weddings/">Weddings at the Ranch</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, <a href="/dinner-date-experience/">Dinner Date Experience</a>. View all <a href="/services/">ranch experiences</a>.</p>',
    metaDescription: 'The Rusty Saddle Bar at Diamond Springs Ranch near Wichita, KS &mdash; on-site bar for events, stays, and bonfire nights. Call (316) 303-6195.',
    faqs: [
      { q: 'What is The Rusty Saddle at Diamond Springs Ranch?', a: 'The Rusty Saddle is the on-site bar at Diamond Springs Ranch &mdash; available during private events, wedding receptions, overnight stays, and dinner date experiences at the ranch.' },
      { q: 'Is The Rusty Saddle open to the public?', a: 'The Rusty Saddle is not a standalone walk-in bar &mdash; it operates as part of ranch experiences and events. For public access, watch for seasonal live music and bonfire night events announced on the ranch&rsquo;s social media.' },
      { q: 'Can we include The Rusty Saddle Bar in our private event at Diamond Springs Ranch?', a: 'Yes. Bar service through The Rusty Saddle is available for weddings, corporate events, birthday parties, and group events. Discuss it when you call (316) 303-6195 to book your event.' },
      { q: 'Does Diamond Springs Ranch host live music events at The Rusty Saddle?', a: 'Yes &mdash; the ranch hosts seasonal live music and bonfire nights. These events include The Rusty Saddle Bar and sell out regularly. Follow @diamondspringsranch on Instagram and Facebook for announcements.' },
      { q: 'Can overnight guests use The Rusty Saddle Bar?', a: 'Overnight guests booking the treehouse, covered wagon, or dinner date experience may have access depending on the date and what is operating that evening. Ask when you call to book your stay.' },
    ],
  },
  {
    slug:       'dinner-date-experience',
    name:       'Dinner Date Experience',
    shortDesc:  'A curated evening at the ranch &mdash; the most unique dinner date near Wichita.',
    icon:       '&#x1F374;',
    cardPhoto:  'card-dinner-date.png',
    heroPhoto:  'IMG_2052-1024x768.jpg',
    insetPhoto: 'IMG_2160-1024x682.jpg',
    insetAlt:   'Dinner date experience at Diamond Springs Ranch',
    photos: [
      { file: 'IMG_2304-1024x683.jpg', alt: 'Evening at Diamond Springs Ranch' },
      { file: 'IMG_2330-1024x682.jpg', alt: 'Dinner date at Diamond Springs Ranch near Wichita' },
      { file: 'IMG_2331-682x1024.jpg', alt: 'Romantic evening on the ranch' },
      { file: 'IMG_2340-1024x682.jpg', alt: 'Diamond Springs Ranch dinner experience' },
    ],
    costRange:  'Call for current pricing &mdash; (316) 303-6195',
    intro:      'The Diamond Springs Ranch Dinner Date Experience is one of the most distinctive evenings available in the Wichita area &mdash; a curated evening on the ranch combining the setting, the animals, and a dining experience that doesn&rsquo;t exist at any restaurant. It&rsquo;s a popular choice for anniversaries, date nights, and special occasions where a table at a restaurant simply won&rsquo;t do.',
    body:       '<p>The Diamond Springs Ranch Dinner Date Experience puts you on a working Kansas ranch at dusk &mdash; the horses in the pasture, the Highland cattle visible across the land, the Sedgwick County sky doing what Kansas skies do in the evening. It combines the ranch setting with a dining experience that does not exist at any restaurant within 30 minutes of Wichita.</p><p>The Dinner Date Experience is a popular choice for anniversaries, milestone birthdays, Valentine&rsquo;s Day, and date nights where a standard restaurant reservation simply is not enough. Couples who book the experience frequently say it is the most memorable evening they have spent in Kansas &mdash; not because of what they ate or what they did, but because of what the setting made possible: a real conversation, an actual moment of presence, away from the city and the routine.</p><p>The Rusty Saddle Bar is on site. The ranch setting is private. And the experience can be combined with an overnight stay in the treehouse or covered wagon for couples who want to extend the evening into a full getaway.</p><h2>Booking the Dinner Date Experience</h2><p>The Dinner Date Experience is by reservation. Call or text (316) 303-6195 to ask about current pricing, availability, and what is included. Weekend dates &mdash; especially in spring and fall &mdash; book quickly. If you&rsquo;re planning for an anniversary or a holiday, calling ahead is recommended.</p><h2>Finding Diamond Springs Ranch in Sedgwick, KS</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS 67135. From downtown Sedgwick &mdash; including the historic Main Street district, Sedgwick Elementary School, and the Sedgwick Community Center &mdash; the ranch is just minutes east on SE 96th Street. The property borders the open ranch land east of the Chisholm Drive corridor, where Sedgwick&rsquo;s rural residential areas transition into working farmland. Guests from the Hillside Drive neighborhood, the SE Prairie View area, and the Oak Ridge subdivision of Sedgwick often walk or bike to the property on the county trail.</p><p>Diamond Springs Ranch has operated in Sedgwick since the property was established by owner Susan Schrag. Built from the ground up, it now holds a 4.9-star Google rating across 281+ verified reviews. The ranch carries general liability insurance and operates as a registered Kansas agritourism business under the Kansas Department of Agriculture. Diamond Springs Ranch has been welcoming guests since 2010 &mdash; over 15 years of operation in Sedgwick County. Owner Susan Schrag holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All activities are led by experienced staff who work with the horses and cattle daily.</p><p>Explore more experiences at Diamond Springs Ranch: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, . View our full list of <a href="/services/">ranch experiences</a> and <a href="/service-areas/">areas we serve</a>.</p>',
    metaDescription: 'Dinner date experience at Diamond Springs Ranch near Wichita, KS. A unique romantic evening on a working Kansas ranch in Sedgwick. Call (316) 303-6195.',
    faqs: [
      { q: 'What is the Dinner Date Experience at Diamond Springs Ranch?', a: 'It&rsquo;s a curated evening at the ranch that goes beyond a standard dinner reservation &mdash; combining the ranch setting, activities, and dining in a way that is genuinely one-of-a-kind in the Wichita area. Call (316) 303-6195 for current details and pricing.' },
      { q: 'Is the Dinner Date Experience good for anniversaries?', a: 'It&rsquo;s one of the most popular anniversary experiences booked at the ranch. The setting &mdash; open Kansas land, working horses, the quiet of the property at dusk &mdash; is unlike anything available at a restaurant.' },
      { q: 'How far in advance should I book the Dinner Date Experience?', a: 'Weekend dates book quickly, especially in spring and fall. Calling at least 2&ndash;3 weeks in advance is recommended for weekend evenings. Call (316) 303-6195 to check availability.' },
      { q: 'Can the Dinner Date Experience be combined with an overnight stay at the ranch?', a: 'Yes &mdash; combining the Dinner Date Experience with a treehouse or covered wagon stay is a popular booking. Call the ranch to package your evening with an overnight.' },
      { q: 'Is the Dinner Date Experience available year-round?', a: 'Availability varies by season. Call (316) 303-6195 to check current scheduling and what&rsquo;s offered during your preferred time of year.' },
    ],
  },
];

// ——————————————————————————————————————————————————————————————
// CITIES — Wichita metro and surrounding areas that send guests
// ——————————————————————————————————————————————————————————————
const CITIES = [
  {
    slug:        'wichita-ks',
    name:        'Wichita',
    state:       'KS',
    zip:         '67202',
    lat:          37.6872,
    lng:         -97.3301,
    intro:       'Diamond Springs Ranch is 17 miles north of Wichita &mdash; the closest working ranch with guided horseback rides, Highland cattle encounters, treehouse stays, and private event rental to any Wichita neighborhood. Most Wichita visitors arrive in 25 minutes via K-15 North.',
    metaDescription: 'Horseback rides, treehouse stays and Highland cattle at Diamond Springs Ranch. 17 miles north of Wichita in Sedgwick, KS. Book your experience today.',
    body:        '<p>Diamond Springs Ranch sits 17 miles north of Wichita at 1734 SE 96th St in Sedgwick, KS &mdash; a 25-minute drive from most Wichita neighborhoods including College Hill, Riverside, Delano, Crown Heights, and the broader metro. For Wichita residents, the ranch is the closest place in the region to ride horses on open ranch land, encounter genuine Highland cattle, or spend the night in a treehouse perched above the Kansas prairie.</p><p>Wichita is home to over 395,000 residents in the metro area, and the demand for authentic outdoor experiences close to the city is real. Diamond Springs Ranch delivers a genuine working-ranch experience rather than a polished approximation &mdash; real horses, real cattle, real open land.</p><p>Wichita corporate groups use the ranch for team-building events and retreats. Wichita families book it for birthday parties, church group outings, and school field trips. Couples from College Hill and Riverside drive up for anniversary horseback rides and treehouse stays. The ranch holds a 4.9-star Google rating across 281 reviews.</p><p>Wichita visitors come to Diamond Springs Ranch from across the city &mdash; College Hill, Riverside, Delano, Crown Heights, Eastborough, Woodlawn, and the Maize corridor all send regular guests. East Wichita families near Douglas Avenue and 21st Street, and north Wichita residents near the Bel Aire city limits, find the 25-minute drive to Sedgwick straightforward via K-15 North from Wichita.</p><h2>Why Do Wichita Residents Choose Diamond Springs Ranch?</h2><p>Diamond Springs Ranch is the only working Western ranch within 30 minutes of Wichita offering horseback rides, Highland cattle encounters, treehouse and covered wagon overnight stays, and full private event rental. The ranch holds a 4.9-star rating across 281+ Google reviews — the most-reviewed ranch experience in the Wichita metro area. Unlike resort-style attractions, Diamond Springs is a genuine working ranch where horses and cattle are present daily and every experience is led by ranch staff who know the land.</p><h2>What Is Diamond Springs Ranch?</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St, Sedgwick, KS 67135 — 15 years in operation under owner Susan Schrag. The ranch carries general liability insurance and is registered as a Kansas agritourism business under the Kansas Department of Agriculture. Susan holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All experiences are by reservation only. Call (316) 303-6195 or email susan@susanschrag.com.</p><h2>Book a Ranch Experience from Wichita</h2><p>Diamond Springs Ranch offers a full range of experiences for Wichita visitors &mdash; all by reservation. Explore what&rsquo;s available: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, and <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full <a href="/services/">list of ranch experiences</a> or call (316) 303-6195 to book.</p>',
    localContext: 'Diamond Springs Ranch is 17 miles north of Wichita via US-81 &mdash; a 25-minute drive from most of the city. Wichita families, couples, and corporate groups regularly make the trip for horseback rides, overnight stays, and private events.',
    neighborhoods: ['College Hill', 'Riverside', 'Delano', 'Crown Heights', 'Eastborough', 'Woodlawn', 'Maize', 'Bel Aire', 'Old Town', 'North Riverside'],
    faqs: [
      { q: 'How far is Diamond Springs Ranch from Wichita, KS?', a: 'Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick, KS &mdash; approximately 17 miles north of downtown Wichita. Most Wichita addresses reach the ranch in 25&ndash;30 minutes via US-81 North.' },
      { q: 'What Wichita neighborhoods regularly visit Diamond Springs Ranch?', a: 'Guests come from College Hill, Riverside, Delano, Crown Heights, Eastborough, Woodlawn, Maize, and Bel Aire &mdash; as well as Derby, Haysville, and Andover. The ranch is accessible from all of Wichita in under 35 minutes.' },
      { q: 'Can Wichita companies use Diamond Springs Ranch for corporate retreats?', a: 'Yes &mdash; corporate retreats and team-building events from Wichita businesses are a regular part of the ranch calendar. The combination of open land, shared physical activities, and genuine Western atmosphere creates a different dynamic than a conference room. Call (316) 303-6195 to discuss your event.' },
      { q: 'Does Diamond Springs Ranch host Wichita family birthday parties?', a: 'Yes. Birthday parties, family reunions, and group outings from Wichita are frequently booked at the ranch. The ranch works for all ages &mdash; from young children meeting the Highland cattle to adults enjoying the covered wagon or bonfire nights.' },
      { q: 'What is the best time of year for Wichita residents to visit Diamond Springs Ranch?', a: 'Spring and fall are the most popular seasons &mdash; ideal weather for horseback rides and outdoor experiences. Summer brings horse summer camps and evening events. Winter availability varies; call (316) 303-6195 to check scheduling.' },
    ],
  },
  {
    slug:        'derby-ks',
    name:        'Derby',
    state:       'KS',
    zip:         '67037',
    lat:          37.5476,
    lng:         -97.2689,
    intro:       'Diamond Springs Ranch is the closest working ranch to Derby, KS &mdash; 35 minutes north on US-81 in Sedgwick. Derby families book guided horseback rides, Highland cattle encounters, treehouse stays, covered wagon nights, and private events at Diamond Springs Ranch.',
    metaDescription: 'Ranch experiences for Derby, KS families at Diamond Springs Ranch in Sedgwick. Horseback rides, Highland cattle, treehouse stays. Call (316) 303-6195.',
    body:        '<p>Derby, KS &mdash; a community of 26,000 residents just south of Wichita &mdash; has direct access to Diamond Springs Ranch via US-81 North. The drive from Derby takes approximately 35&ndash;40 minutes. Derby residents from South Derby, Derby Junction, Pleasant Valley, and Wheatland Estates book the ranch for birthday parties, school group outings, and corporate team-building events.</p><p>The ranch holds a 4.9-star Google rating across 281 reviews. Derby families making the drive for the first time almost always leave planning a return visit. Young families respond to the combination of real animals, open land, and activities that do not involve a screen.</p><p>Derby families from South Derby, the High Park neighborhood near Rock River Rapids, and the residential corridors along Rock Road and Madison Avenue make the trip to Diamond Springs Ranch regularly. Derby USD 260 school groups and McConnell Air Force Base families visiting the area have discovered that the 35-minute drive northwest on US-81 is one of the most worthwhile short trips in the Wichita metro.</p><h2>Why Do Derby Families Drive to Diamond Springs Ranch?</h2><p>Derby has Rock River Rapids and Chicken N Pickle, but there is no working ranch within Derby city limits. Diamond Springs Ranch is the closest authentic horseback ride, Highland cattle encounter, and overnight stay experience to Derby — under 35 minutes north on US-81. The ranch holds a 4.9-star Google rating across 281+ verified reviews and has welcomed South Derby families, Rock Road corridor residents, and McConnell AFB families for over 15 years.</p><h2>What Is Diamond Springs Ranch?</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St, Sedgwick, KS 67135 — 15 years in operation under owner Susan Schrag. The ranch carries general liability insurance and is registered as a Kansas agritourism business under the Kansas Department of Agriculture. Susan holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All experiences are by reservation only. Call (316) 303-6195 or email susan@susanschrag.com.</p><h2>Book a Ranch Experience from Derby</h2><p>Diamond Springs Ranch offers a full range of experiences for Derby visitors &mdash; all by reservation. Explore what&rsquo;s available: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, and <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full <a href="/services/">list of ranch experiences</a> or call (316) 303-6195 to book.</p>',
    localContext: 'Derby families looking for an authentic outdoor experience north of Wichita frequently book Diamond Springs Ranch for birthday parties, family outings, and horseback rides. The drive from Derby is approximately 35&ndash;40 minutes via US-81 North.',
    neighborhoods: ['South Derby', 'Derby Junction', 'Pleasant Valley', 'West Derby', 'Wheatland Estates', 'Derby Hills', 'Meadowlark Hills', 'Buckner Heights'],
    faqs: [
      { q: 'How far is Diamond Springs Ranch from Derby, KS?', a: 'Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick &mdash; approximately 35&ndash;40 minutes north of Derby via US-81 North.' },
      { q: 'What activities can Derby families do at Diamond Springs Ranch?', a: 'Derby families regularly book guided horseback trail rides, Highland cattle encounters, birthday party events, and family reunions at the ranch. The covered wagon and luxury treehouse overnight stays are popular for Derby couples.' },
      { q: 'Does Diamond Springs Ranch host Derby school groups and field trips?', a: 'Yes. School field trips and educational group visits from Derby are welcome at the ranch. The Highland cattle encounter and horseback rides are popular for school groups. Call (316) 303-6195 to plan a group visit.' },
      { q: 'Can Derby corporations use Diamond Springs Ranch for team-building?', a: 'Yes &mdash; corporate team-building and company retreat bookings from Derby businesses are accommodated. Call (316) 303-6195 to discuss your group.' },
      { q: 'Is Diamond Springs Ranch worth the drive from Derby, KS?', a: 'Based on 281 Google reviews averaging 4.9 stars, guests from across the Wichita metro &mdash; including Derby &mdash; consistently say yes. The 35-minute drive puts you on open Kansas ranch land that does not exist anywhere closer to Derby.' },
    ],
  },
  {
    slug:        'haysville-ks',
    name:        'Haysville',
    state:       'KS',
    zip:         '67060',
    lat:          37.5651,
    lng:         -97.3519,
    intro:       'Diamond Springs Ranch is 35 minutes north of Haysville on US-81 &mdash; the closest working ranch experience to southern Sedgwick County. Haysville families book guided horseback rides, Highland cattle encounters, treehouse overnight stays, and private events.',
    metaDescription: 'Ranch experiences for Haysville, KS families at Diamond Springs Ranch in Sedgwick. Horseback rides, Highland cattle, and more. Call (316) 303-6195.',
    body:        '<p>Haysville, KS &mdash; a community of 11,500 residents on Wichita&rsquo;s south side &mdash; sits about 35 minutes south of Diamond Springs Ranch via US-81 North. Neighborhoods including South Haysville, Lake Afton Community, and the Clearwater Road Corridor all have straightforward access heading north on US-81.</p><p>Church groups and faith communities from Haysville use the ranch for outdoor events, retreats, and summer programming. School groups visit for field trips combining animal encounters with open-air learning. Haysville families book horseback rides for birthdays, anniversary outings, and weekend visits with out-of-town relatives. The ranch holds a 4.9-star Google rating across 281 reviews.</p><p>Haysville families from the South Grove Road corridor, the Red Rock neighborhood, and the residential areas near Haysville Middle School make the drive to Diamond Springs Ranch for ranch experiences they can&rsquo;t find closer to home. The 35-minute route north on US-81 takes Haysville visitors through open Sedgwick County land &mdash; and the scenery along the way is part of the experience.</p><h2>Why Do Haysville Residents Visit Diamond Springs Ranch?</h2><p>Haysville is a tight-knit residential community south of Wichita with no working ranch experiences within city limits. Diamond Springs Ranch gives Haysville families, school groups, and corporate teams access to authentic Kansas ranch life — guided horseback rides, Highland cattle interactions, bonfire nights, treehouse stays, and full private event rental — in a 35-minute drive north on US-81. The ranch has hosted Haysville USD 261 school groups and regularly welcomes families from the South Grove Road and Red Rock neighborhoods.</p><h2>What Is Diamond Springs Ranch?</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St, Sedgwick, KS 67135 — 15 years in operation under owner Susan Schrag. The ranch carries general liability insurance and is registered as a Kansas agritourism business under the Kansas Department of Agriculture. Susan holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All experiences are by reservation only. Call (316) 303-6195 or email susan@susanschrag.com.</p><h2>Book a Ranch Experience from Haysville</h2><p>Diamond Springs Ranch offers a full range of experiences for Haysville visitors &mdash; all by reservation. Explore what&rsquo;s available: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, and <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full <a href="/services/">list of ranch experiences</a> or call (316) 303-6195 to book.</p>',
    localContext: 'Haysville residents are a short drive from Diamond Springs Ranch &mdash; heading north on US-81 puts you at the ranch in about 35 minutes. Church groups, school field trips, and family events from Haysville are a regular part of the ranch schedule.',
    neighborhoods: ['South Haysville', 'Lake Afton Community', 'West Haysville', 'Haysville Crossing', 'South Seneca Corridor', 'Airport Road Area', 'Clearwater Road Corridor', 'Haysville Junction'],
    faqs: [
      { q: 'How far is Diamond Springs Ranch from Haysville, KS?', a: 'Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick &mdash; approximately 35 minutes north of Haysville via US-81 North.' },
      { q: 'Can Haysville church groups book events at Diamond Springs Ranch?', a: 'Yes &mdash; church groups and faith community events from Haysville are welcome at the ranch. Call (316) 303-6195 for scheduling.' },
      { q: 'Does Diamond Springs Ranch host Haysville school field trips?', a: 'Yes. School field trips from Haysville schools visit the ranch for horseback ride experiences and Highland cattle encounters. Call (316) 303-6195 to discuss scheduling.' },
      { q: 'What is the best way to get to Diamond Springs Ranch from Haysville?', a: 'Head north on US-81 from Haysville through Wichita and continue north to Sedgwick. The ranch address is 1734 SE 96th St, Sedgwick, KS 67135. Drive time is approximately 35 minutes.' },
      { q: 'Are Diamond Springs Ranch experiences good for Haysville families with young children?', a: 'Yes &mdash; the ranch is accessible for all ages. Young children participate in guided horseback rides and Highland cattle encounters regularly.' },
    ],
  },
  {
    slug:        'andover-ks',
    name:        'Andover',
    state:       'KS',
    zip:         '67002',
    lat:          37.6953,
    lng:         -97.1351,
    intro:       'Diamond Springs Ranch is the closest working ranch to Andover, KS &mdash; a 35-minute drive west on US-54 to Sedgwick. Andover families and corporate teams book horseback rides, Highland cattle experiences, treehouse stays, and private event rental at Diamond Springs Ranch.',
    metaDescription: 'Ranch experiences for Andover, KS families at Diamond Springs Ranch in Sedgwick, KS. Horseback rides, retreats, treehouse stays. Book today.',
    body:        '<h2>What Ranch Experiences Are Available Near Andover, KS?</h2><p>Andover, KS sits 30 miles east of Diamond Springs Ranch — a 35-minute drive via US-54 and K-15 through the Sedgwick County agricultural corridor. Andover is one of the Wichita metro&rsquo;s fastest-growing communities, with over 16,000 residents in Auburn Hills, Rolling Meadows, Tallgrass Estates, Rock Hills, and Windmill Creek. As Andover has grown, it has remained predominantly residential and suburban — there are no working ranches, horseback ride operations, or Highland cattle farms within Andover city limits. Diamond Springs Ranch fills that gap for the entire east side of the metro.</p><p>Andover families book the ranch for birthday parties, church and school group outings, couples anniversaries, and summer experiences that get kids away from screens and onto a working ranch. Corporate teams from Andover&rsquo;s growing business corridor use the ranch for quarterly retreats — the private event rental includes the full ranch property and is 30 minutes from east Wichita without highway traffic. The ranch has welcomed Andover families from the 21st Street and Central Avenue residential area, Rock Hills, and Tallgrass Estates repeatedly over 15 years of operation.</p><p>Andover guests frequently note in reviews that the drive is &ldquo;worth every minute&rdquo; — the ranch experience is not replicated anywhere closer to Andover. Diamond Springs Ranch holds a 4.9-star Google rating across 281+ verified reviews, with multiple reviews specifically from Andover and east Wichita guests.</p><h2>What Is Diamond Springs Ranch?</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St, Sedgwick, KS 67135 — 15 years in operation under owner Susan Schrag. The ranch carries general liability insurance and is registered as a Kansas agritourism business under the Kansas Department of Agriculture. Susan holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All experiences are by reservation only. Call (316) 303-6195 or email susan@susanschrag.com.</p><h2>Book a Ranch Experience from Andover</h2><p>Diamond Springs Ranch offers a full range of experiences for Andover visitors — all by reservation. Explore what&rsquo;s available: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, and <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full <a href="/services/">list of ranch experiences</a> or call (316) 303-6195 to book.</p>',
    localContext: 'Andover is one of the fastest-growing communities in the Wichita metro. Families and corporate groups seeking unique outdoor experiences regularly book Diamond Springs Ranch, approximately 30 minutes west via US-54 / K-15.',
    neighborhoods: ['Auburn Hills', 'Rolling Meadows', 'Tallgrass Estates', 'Windmill Creek', 'Andover Trails', 'East Andover', 'College Hill East', 'Prairie Creek'],
    faqs: [
      { q: 'How far is Diamond Springs Ranch from Andover, KS?', a: 'Diamond Springs Ranch is located at 1734 SE 96th St in Sedgwick &mdash; approximately 30 minutes west of Andover via US-54 West to US-81 North.' },
      { q: 'Can Andover businesses use Diamond Springs Ranch for corporate retreats?', a: 'Yes &mdash; corporate retreats and team-building events from Andover companies are regularly booked at the ranch. Call (316) 303-6195 to discuss your event.' },
      { q: 'What ranch experiences are available for Andover families?', a: 'Andover families book guided horseback trail rides, Highland cattle encounters, birthday parties, and family reunion events. The luxury treehouse and covered wagon overnight stays are popular for Andover couples.' },
      { q: 'Does Diamond Springs Ranch host Andover school and scout groups?', a: 'Yes &mdash; scout groups and school field trips from Andover are welcome at the ranch. Call (316) 303-6195 to plan a group visit.' },
      { q: 'What makes Diamond Springs Ranch worth the drive from Andover?', a: 'Andover has excellent amenities, but a working ranch with horseback rides, Highland cattle, and a treehouse overnight is not among them. Diamond Springs Ranch is the closest place in the region to find that combination, rated 4.9 stars across 281 Google reviews.' },
    ],
  },
  {
    slug:        'newton-ks',
    name:        'Newton',
    state:       'KS',
    zip:         '67114',
    lat:          38.0467,
    lng:         -97.3453,
    intro:       'Diamond Springs Ranch is 12 miles south of Newton, KS on US-81 &mdash; the shortest drive to a working ranch horseback ride and overnight stay from Harvey County. Newton families, Bethel College groups, and Harvey County residents book trail rides, treehouse stays, and private events at Diamond Springs Ranch.',
    metaDescription: 'Ranch experiences for Newton, KS at Diamond Springs Ranch in Sedgwick &mdash; just 12 miles away on US-81. Horseback rides, treehouse stays, and more.',
    body:        '<p>Newton, KS &mdash; Harvey County seat with 18,700 residents &mdash; sits 12 miles north of Diamond Springs Ranch on US-81, making it the community with the shortest drive to the ranch in the entire region. Newton residents from North Newton, Newton Junction, and the Hesston area can reach Diamond Springs Ranch in under 15 minutes.</p><p>Church groups and faith communities from Newton and Hesston regularly book the ranch for outdoor retreats and group events. Newton families use the ranch for birthday outings, school field trips, and anniversary experiences. The short drive makes last-minute bookings more accessible for Newton residents than for anyone else in the metro. The ranch holds a 4.9-star Google rating across 281 reviews.</p><p>Diamond Springs Ranch is a natural draw for Newton families. The Bethel College neighborhood along Main Street, the Athletic Park area on the north side of Newton, and the residential streets along Broadway &mdash; these are home to families who want authentic Kansas ranch experiences without a long drive. Newton&rsquo;s Chisholm Trail heritage makes ranch culture feel like home ground here, and the 12-mile drive south on US-81 to Diamond Springs Ranch takes less time than getting from one side of Wichita to the other.</p><h2>Why Do Newton Families Visit Diamond Springs Ranch?</h2><p>Newton&rsquo;s Chisholm Trail heritage runs deep — the city was a major cattle-drive terminus in the 1870s — making Diamond Springs Ranch a natural cultural connection for Newton residents who want to reconnect with Kansas ranching history. The 12-mile drive south on US-81 takes Newton visitors straight into Sedgwick County ranch country. Diamond Springs Ranch holds a 4.9-star Google rating across 281+ Google reviews and has welcomed Newton families, Bethel College groups, and Harvey County residents for 15 years.</p><h2>What Is Diamond Springs Ranch?</h2><p>Diamond Springs Ranch is located at 1734 SE 96th St, Sedgwick, KS 67135 — 15 years in operation under owner Susan Schrag. The ranch carries general liability insurance and is registered as a Kansas agritourism business under the Kansas Department of Agriculture. Susan holds equine handling certifications and the ranch maintains current Kansas Department of Wildlife and Parks compliance. All experiences are by reservation only. Call (316) 303-6195 or email susan@susanschrag.com.</p><h2>Book a Ranch Experience from Newton</h2><p>Diamond Springs Ranch offers a full range of experiences for Newton visitors &mdash; all by reservation. Explore what&rsquo;s available: <a href="/guided-horseback-rides/">Guided Horseback Rides</a>, <a href="/highland-cattle-experience/">Highland Cattle Experience</a>, <a href="/luxury-treehouse-stay/">Luxury Treehouse Stay</a>, <a href="/covered-wagon-stay/">Covered Wagon Stay</a>, <a href="/private-events/">Private Events &amp; Rentals</a>, and <a href="/dinner-date-experience/">Dinner Date Experience</a>. View our full <a href="/services/">list of ranch experiences</a> or call (316) 303-6195 to book.</p>',
    localContext: 'Newton is 12 miles north of Diamond Springs Ranch on US-81 &mdash; the closest significant community to the property. Newton residents have the shortest drive of anyone in the region to experience the ranch.',
    neighborhoods: ['North Newton', 'Newton Junction', 'Newton West', 'Harvey County East', 'Sedgwick Area', 'Walton Community', 'Burrton', 'Hesston'],
    faqs: [
      { q: 'How close is Diamond Springs Ranch to Newton, KS?', a: 'Diamond Springs Ranch at 1734 SE 96th St in Sedgwick is approximately 12 miles south of Newton on US-81 &mdash; a drive of about 15 minutes. Newton is the closest significant community to the ranch.' },
      { q: 'Can Newton church groups book the ranch for outdoor retreats?', a: 'Yes &mdash; church groups and faith community events from Newton and Harvey County are regularly booked at Diamond Springs Ranch. Call (316) 303-6195 to discuss your event.' },
      { q: 'What activities does Diamond Springs Ranch offer for Newton families?', a: 'Newton families book guided horseback trail rides, Highland cattle encounters, birthday parties, and family reunion events. Treehouse and covered wagon overnight stays are available for couples and families.' },
      { q: 'Can Newton residents make a last-minute reservation at Diamond Springs Ranch?', a: 'The proximity of Newton to the ranch makes last-minute booking more feasible than for most other communities. Call or text (316) 303-6195 to check current availability.' },
      { q: 'What makes Diamond Springs Ranch the best option for Newton-area families?', a: 'At 12 miles away, Newton families have easier access to Diamond Springs Ranch than anyone else in the region. No long drive &mdash; just a quick trip south on US-81 to a working ranch with horseback rides, Highland cattle, and the only luxury treehouse overnight in the area.' },
    ],
  },
];

// ——————————————————————————————————————————————————————————————
// SERVICE FAQS — general FAQs for the homepage / about page
// ——————————————————————————————————————————————————————————————
const SERVICE_FAQS = [
  { q: 'Where is Diamond Springs Ranch located?', a: 'Diamond Springs Ranch is located at 1734 SE 96th St, Sedgwick, KS 67135 &mdash; approximately 17 miles north of downtown Wichita on US-81. The drive from most Wichita addresses takes 25&ndash;30 minutes.' },
  { q: 'Do I need a reservation to visit Diamond Springs Ranch?', a: 'Yes &mdash; all activities at Diamond Springs Ranch are by reservation. The ranch does not accommodate walk-in visitors. Call or text (316) 303-6195 to book your experience.' },
  { q: 'What activities are available at Diamond Springs Ranch?', a: 'The ranch offers guided horseback trail rides, sunset trail rides, Highland cattle encounters, riding lessons, horse summer camps, luxury treehouse overnight stays, covered wagon stays, private events (weddings, corporate retreats, family reunions), dinner date experiences, bonfires, and live music events seasonally.' },
  { q: 'Is Diamond Springs Ranch suitable for corporate team-building events?', a: 'Yes &mdash; corporate retreats and team-building events are regularly hosted at the ranch. Getting a team onto a working ranch in an outdoor setting produces a completely different dynamic than a conference room. Call (316) 303-6195 to discuss your event.' },
  { q: 'Does Diamond Springs Ranch host weddings?', a: 'Yes. The ranch hosts wedding receptions on the property. The open land, working horses, and authentic Western setting create a backdrop for weddings that can&rsquo;t be replicated at a venue property. Call to discuss your date and vision.' },
];

module.exports = { CLIENT, SERVICES, CITIES, REVIEWS, DIFFERENTIATORS, SERVICE_FAQS };
